### ISSUE TITLE
Add: Axios

### ISSUE THREAD

**Issue by sabesansathananthan** [sabesansathananthan/React-GitHub-Resume#1]
Replace Axios instead of Fetch API. (src->pages->Resume.js).  Attach your working Screenshots with PR

**Comment by bhagatparwinder** [comment]
I can do this.

**Comment by sabesansathananthan** [comment]
I will assign you for this project. Don't forget to give a star

**Comment by bhagatparwinder** [comment]
Please assign it to someone else for now.

**Comment by sabesansathananthan** [comment]
sure.

**Comment by HyperTHD** [comment]
If it's available, I'd like to take a shot at this

**Comment by sabesansathananthan** [comment]
@HyperTHD Could you try this? I will assign you. Don't forget to give a star to this repo

**Comment by sattyamjjain** [comment]
I want to contribute to the issue, If it possible, Assign to me..

**Comment by sabesansathananthan** [comment]
@sattyamjjain This issue already assigned to @HyperTHD anyway thanks. If he couldn't then you could try. Wait for his response. Or I will open a new issue. Thank you for your support.
