### ISSUE TITLE
Fix: Typo Errors

### ISSUE THREAD

**Issue by sabesansathananthan** [sabesansathananthan/React-GitHub-Resume#10]
This project UI may have typo errors. check all the files in the src folder and correct the grammar mistakes.

**Comment by vj-abishek** [comment]
I can work on it. Could you please assign me?

**Comment by sabesansathananthan** [comment]
I will assign you. Don't forget to give a star to this repo.

**Comment by vj-abishek** [comment]
@sabesansathananthan need to do other changes?

**Comment by vj-abishek** [comment]
https://github.com/sabesansathananthan/React-GitHub-Resume/issues/10.patch

https://github.com/sabesansathananthan/React-GitHub-Resume/issues/10.diff

**Comment by sabesansathananthan** [comment]
Thank you for your PR
