### ISSUE TITLE
Feat: react-i18next

### ISSUE THREAD

**Issue by sabesansathananthan** [sabesansathananthan/React-GitHub-Resume#17]
add translation for this project.  Need to add a Language dropdown menu as well

**Comment by erdemuslu** [comment]
I'll do this. Can you assign me? Thanks.

**Comment by sabesansathananthan** [comment]
I will assign you. Don't forget to star this repo

**Comment by erdemuslu** [comment]
I created a Header section and Dropdown for language UI.

This is the PR: #20 

Can you check and merge it? After that, I'll implement the react-i18next implemantation.

Thanks.

**Comment by sabesansathananthan** [comment]
Nice. I checked. Could you please update the rest part I will merge with the i18next PR

**Comment by erdemuslu** [comment]
I updated. Thanks.

**Comment by esau-morais** [comment]
> I updated. Thanks.

If you need help to create the translations (json) files, we can call the same people from the issue #15

**Comment by sabesansathananthan** [comment]
Nice @esau-morais Could you please review it.

**Comment by sabesansathananthan** [comment]
Thank you @erdemuslu for your PR and thank you @esau-morais  for your review. I merged the PR
