### ISSUE TITLE
Docs Add: Code_of_Conduct and Contributor guidelines

### ISSUE THREAD

**Issue by orama254** [sabesansathananthan/React-GitHub-Resume#5]
Add code of conduct and contributor guidelines file to align with Github's [recommended community standards](https://opensource.guide/)

**Screenshot**

![community profile_reactgithubresume](https://user-images.githubusercontent.com/50571688/95049106-cc55eb80-06f1-11eb-8062-d7fd06b1479d.JPG)

Would be delighted to take up this task if needed

**Comment by sabesansathananthan** [comment]
@orama254 Nice. Looking for a contributor.

**Comment by orama254** [comment]
@sabesansathananthan I'd be delighted to take up this task

**Comment by sabesansathananthan** [comment]
Sure. Make a PR.
