### ISSUE TITLE
Docs: update README

### ISSUE THREAD

**Issue by sabesansathananthan** [sabesansathananthan/React-GitHub-Resume#9]
Update Readme with more information.

**Comment by esau-morais** [comment]
Thank you for request this issue! I can get this and make your README better.

_Note: Please, assign me to this issue to prevent spam_

**Comment by sabesansathananthan** [comment]
Sure. I will assign you. Don't forget to give a star to this repo

**Comment by ritwikchakraborty123** [comment]
Sir I want to contribute also

**Comment by sabesansathananthan** [comment]
Wait for the @esau-morais  PR. If you could do further improvements after merged @esau-morais PR. You can do. Thank you @ritwikchakraborty123

**Comment by sabesansathananthan** [comment]
@esau-morais Thank you for your PR

**Comment by sabesansathananthan** [comment]
@ritwikchakraborty123 Can You further improve it

**Comment by esau-morais** [comment]
> @ritwikchakraborty123 Can You further improve it

I think you can close this issue and focus in the #15
